# Generated by Django 3.2.5 on 2021-07-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_category', models.CharField(choices=[('maktab home work', 'maktab home work'), ('improve django skill', 'improve django skill'), ('react exe', 'react exe')], max_length=100)),
                ('empty_category', models.CharField(choices=[('front exe', 'front exe'), ('fun', 'fun'), ('fun name', 'fun name'), ('new category', 'new category')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('HIGH', 'HIGH'), ('MIDDLE', 'MIDDLE'), ('LOW', 'LOW')], max_length=200)),
                ('due_date_time', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.category')),
            ],
        ),
    ]
