# Generated by Django 3.2.5 on 2021-07-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='full_category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='empty_category',
        ),
    ]
