# Generated by Django 3.2.5 on 2021-07-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210730_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('maktab home work', 'maktab home work'), ('improve django skill', 'improve django skill'), ('react exe', 'react exe')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
