# Generated by Django 3.2.5 on 2021-07-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210731_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('sports ', 'sports'), ('ToBuy', 'ToBuy'), ('House Chores', 'House Chores'), ('Django Project', 'Django Project'), ('undecided', 'undecided')], default='undecided', max_length=100),
        ),
    ]
